mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('tinysite.urls')),
    path('admin/', admin.site.urls),
]

mysite/tinysite/urls.py
'''
相关资料：
https://docs.djangoproject.com/zh-hans/2.0/topics/http/urls/
'''

from django.urls import path

from . import views

app_name = 'tinysite'
urlpatterns = [
    path('', views.index, name='index'),
    # path('column/<slug:column_slug>/', views.column_detail, name='column'),
    path('<slug:category_slug>/<slug:column_slug>/<slug:article_slug>', views.article_detail, name='article'),
]

mysite/tinysite/models.py
# -*- coding: utf-8 -*-
'''
相关资料：
https://docs.djangoproject.com/zh-hans/2.0/topics/db/models/
https://docs.djangoproject.com/zh-hans/2.0/topics/db/queries/
'''

from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField('栏目分类', max_length=100)
    slug = models.SlugField('类别网址', max_length=256, db_index=True, default='category')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "栏目分类"
        verbose_name_plural = "栏目分类"


class Column(models.Model):
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL, verbose_name = "所属分类")
    name = models.CharField('栏目名称', max_length=100)
    slug = models.SlugField('栏目网址', max_length=256, db_index=True)
    intro = models.TextField('栏目简介', default='')

    nav_display = models.BooleanField('导航显示', default=True)

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse('tinysite:column', args=[str(self.slug,)])

    class Meta:
        verbose_name = "栏目"
        verbose_name_plural = "栏目"


class Article(models.Model):
    column = models.ForeignKey(Column, on_delete=models.CASCADE, verbose_name = "所属栏目")
    title = models.CharField('标题', max_length=200)
    slug = models.SlugField('网址', max_length=200)
    content = models.TextField('内容', default='')
    pub_time = models.DateTimeField('发表时间', auto_now_add=True)
    update_time = models.DateTimeField('更新时间', auto_now=True, null=True)
    views = models.PositiveIntegerField('浏览量', default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tinysite:article', args=[self.column.category.slug, self.column.slug, str(self.slug)])

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = "文章"

    # 浏览量增加函数
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

mysite/tinysite/views.py
'''
相关资料：
https://docs.djangoproject.com/zh-hans/2.0/topics/http/views/
'''

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, render

from .models import Category, Column, Article


def index(request):
    categories = Category.objects.all()
    nav_display_columns = Column.objects.filter(nav_display=True)
    return render(request, 'index.html', {
        'categories': categories,
        'nav_display_columns': nav_display_columns,
    })


# def column_detail(request, column_slug):
#     column = get_object_or_404(Column, slug=column_slug)
#
#     article_list = column.article_set.all()
#     paginator = Paginator(article_list, 1)  # Show 25 contacts per page
#
#     page = request.GET.get('page')
#     article_page = paginator.get_page(page)
#
#     return render(request, 'tinysite/column.html', {
#         'column': column,
#         'article_page': article_page,
#     })


def article_detail(request, category_slug, column_slug, article_slug):
    category = get_object_or_404(Category, slug=category_slug)
    column = get_object_or_404(Column, slug=column_slug)
    article = get_object_or_404(Article, slug=article_slug)

    # 浏览量 +1
    article.increase_views()

    article_list = [ a for a in Article.objects.filter(column=column.id) ]
    current_article_index = article_list.index(article)

    if len(article_list) < 2:
        previous_article = None
        next_article = None

    else:
        if current_article_index == 0:
            previous_article = None
            next_article = article_list[1]

        elif current_article_index > 0 and current_article_index < len(article_list) - 1:
            previous_article = article_list[current_article_index - 1]
            next_article = article_list[current_article_index + 1]
        else:
            previous_article = article_list[current_article_index - 1]
            next_article = None

    return render(request, 'tinysite/article.html', {
        'category': category,
        'column': column,
        'article': article,
        'previous_article': previous_article,
        'next_article': next_article,
    })

mysite/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<!-- 加载static目录 -->
{% load static %}

<head>
    <meta charset="utf-8">
    <!-- IE8 的兼容模式 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- 为移动端窗口优化 -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block title %}
    <title>邢为栋的小站</title>
    {% endblock %}

    <!-- 说明信息 -->
    <meta name="author" content="邢为栋"/>
    <meta name="description" content="小站用于发布个人整理的学习教程和经验，以及其他爱好的东西。" />

    <!-- 告诉浏览器页面是否为手持设备优化，会被MobileOptimized覆盖 -->
    <meta name="HandheldFriendly" content="True" />
    <meta name="MobileOptimized" content="320" />

    <!-- 引入 Bootstrap 3.3.7 -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'tinysite/css/style.min.css' %}" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <!-- jQuery (Bootstrap 插件需要引入) -->
    <script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
    <!-- 包含了所有编译插件 -->
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- 为重复的网址或版本指定权威网页 -->
    <link rel="canonical" href="http://www.xingweidong.com/" />
    <!-- 参考https://support.google.com/webmasters/answer/1663744?hl=zh-Hans -->
    <link rel="next" href="http://www.xingweidong.com/page/2/" />

    <!-- Favicons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'tinysite/assets/ico/taiji.png' %}">
    <link rel="shortcut icon" href="{% static 'tinysite/assets/ico/taiji.png' %}">

    {% block extra %}
    {% endblock %}
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="http://www.xingweidong.com/"><span class="glyphicon glyphicon-home"></span></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
            {% for category in categories %}
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    {{ category.name }}<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    {% for column in category.column_set.all %}
                    {% if column in nav_display_columns %}
                    <!--<li><a href="{{ column.get_absolute_url }}"> {{ column.name }} </a></li>-->
                    <li><a href="{{ column.article_set.all.0.get_absolute_url }}" class="tooltip-test"
                           data-toggle="tooltip" data-placement="right" title="{{ column.intro }}">
                        {{ column.name }} </a></li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </li>
            {% endfor %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="https://github.com/Xingwd"><img src="{% static 'tinysite/assets/ico/github24.png' %}"></a></li>
            <li><a href="mailto:614968414@qq.com"><img src="{% static 'tinysite/assets/ico/at24.png' %}"></a></li>
        </ul>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}

<!-- 页尾-->
<div class="jumbotron text-center" style="margin-bottom:0; background:#202020; color:#959595; padding: 15px;">
    <p style="font-weight: 500; font-size: 12px;">部分文字和图片来自于网络，如有侵权，请告知删除。</p>
    <p style="font-weight: 500; font-size: 12px;">小站提供的内容来自于个人的学习笔记，可用于学习参考，但不保证内容的正确性。通过使用本站内容随之而来的风险与本站无关。</p>
</div>

</body>
</html>

mysite/templates/index.html
<!DOCTYPE html>
<html lang="zh-CN">
{% extends 'base.html' %}
<!-- 加载static目录 -->
{% load static %}

<head>
    {% block title %}
    <title>邢为栋的小站</title>
    {% endblock %}

    {% block extra %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/4.1.0/lazysizes.min.js" async=""></script>
    {% endblock %}
</head>

<body>

{% block content %}
<!-- first -->
<div class="content lazyload" data-bg="{% static 'tinysite/images/bg-first.png' %}">
    <div class="container first">
        <div class="row">
            <nav class="col-xs-12">
                <p><span>心无界 行无疆</span></p>
            </nav>
        </div>
        <div class="row">
            <nav class="col-xs-12" style="font-size: 20px; padding: 50px 0 0">
                <p style="text-indent: 8%;">你好，我是邢为栋</p>
                <p style="text-indent: 12%;">欢迎来到我的小站</p>
            </nav>
        </div>
    </div>
</div>
<div class="jumbotron" style="margin-bottom:0">
    <div class="container txt">
        <div class="row">
            <nav class="col-xs-4">
                <h1>关于小站</h1>
            </nav>
            <nav class="col-xs-8">
                <p>小站建设是为了学以致用，同时将所学所得编写成学习笔记和经验，发布到小站，希望可以对光临小站的朋友有所帮助。</p>
                <p>小站并非专业的教学网站，站内内容仅供参考。</p>
                <p>愿与君共勉！</p>
            </nav>
        </div>
    </div>
</div>
<!-- second -->
<div class="content lazyload" data-bg="{% static 'tinysite/images/bg-second.png' %}">
    <div class="container second">
        <div class="row">
            <nav class="col-xs-12">
                <p style="text-indent: -12%;">淡泊以明志</p>
                <p style="text-indent: 12%;">宁静以致远</p>
            </nav>
        </div>
    </div>
</div>
<div class="jumbotron" style="margin-bottom:0">
    <div class="container txt">
        <div class="row">
            <nav class="col-xs-4">
                <h1>明心见性</h1>
            </nav>
            <nav class="col-xs-8">
                <p>追逐之心惟见前方</p>
                <p style="text-indent: 5%;">淡然之心可见万物</p>
            </nav>
        </div>
    </div>
</div>
<!-- third -->
<div class="content lazyload" data-bg="{% static 'tinysite/images/bg-third.png' %}">
    <div class="container third">
        <div class="row">
            <nav class="col-xs-12">
                <p>水利万物而不争</p>
            </nav>
        </div>
    </div>
</div>
<div class="jumbotron" style="margin-bottom:0">
    <div class="container txt">
        <div class="row">
            <nav class="col-xs-4">
                <h1>上善若水</h1>
            </nav>
            <nav class="col-xs-8">
                <p>至善至柔，无争无为</p>
                <p style="text-indent: 5%;">心如止水，方可逍遥自在</p>
            </nav>
        </div>
    </div>
</div>

<script>
document.addEventListener('lazybeforeunveil', function(e){
    var bg = e.target.getAttribute('data-bg');
    if(bg){
        e.target.style.backgroundImage = 'url(' + bg + ')';
    }
});
</script>
{% endblock %}

</body>

</html>

mysite/tinysite/templates/tinysite/article.html
<!DOCTYPE html>
<html lang="zh-CN">
{% extends 'base.html' %}
<!-- 加载static目录 -->
{% load static %}

{% load markdown_deux_tags %}

<head>
    {% block title %}
    <title>邢为栋的小站</title>
    {% endblock %}

    {% block extra %}
    <link rel="stylesheet" type="text/css" href="{% static 'tinysite/css/custom-markdown.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'tinysite/css/pygments-css-monokai.css' %}" />
    {% endblock %}
</head>

<body>

{% block content %}
<div class="jumbotron" style="margin-bottom:0">
    <div class="container">
        <div class="row">
            <nav class="col-sm-3">
                <div class="container-fluid">
                <div class="container-fluid collapse navbar-collapse">
                    <h3>{{ column.name }}</h3>
                <ul class="nav nav-pills nav-stacked">
                    {% for a in column.article_set.all %}
                    <li id="{{ a.id }}"><a href="{{ a.get_absolute_url }}">{{ a.title }}</a></li>
                    {% endfor %}
                </ul>
                </div>
                </div>
            </nav>
            <div class="col-sm-9" style="margin-top:50px">
                <!-- 翻页，内容上面 -->
                <ul class="pager">
                    {% if previous_article is None %}
                    <li class="previous disabled"><a href=""><span class="glyphicon glyphicon-chevron-left"></span> 前面没有了</a></li>
                    {% else %}
                    <li class="previous"><a href="{{ previous_article.get_absolute_url }}"><span class="glyphicon glyphicon-chevron-left"></span> {{ previous_article.title }}</a></li>
                    {% endif %}
                    {% if next_article is None %}
                    <li class="next disabled"><a href="">后面没有了 <span class="glyphicon glyphicon-chevron-right"></span></a></li>
                    {% else %}
                    <li class="next"><a href="{{ next_article.get_absolute_url }}">{{ next_article.title }} <span class="glyphicon glyphicon-chevron-right"></span></a></li>
                    {% endif %}
                </ul>
                <div class="text-center" style="margin-bottom:25px;">
                    <ul class="list-inline">
                        <li class="list-inline-item">更新时间：{{ article.update_time }}</li>
                        <li> </li>
                        <li class="list-inline-item">浏览量：{{ article.views }}</li>
                    </ul>
                </div>
                <div class="markdown-body">
                    <!-- 使用markdown语法解释章节内容-->
                    {{ article.content|markdown }}
                </div>
                <!-- 翻页，内容下面 -->
                <ul class="pager">
                    {% if previous_article is None %}
                    <li class="previous disabled"><a href=""><span class="glyphicon glyphicon-chevron-left"></span> 前面没有了</a></li>
                    {% else %}
                    <li class="previous"><a href="{{ previous_article.get_absolute_url }}"><span class="glyphicon glyphicon-chevron-left"></span> {{ previous_article.title }}</a></li>
                    {% endif %}
                    {% if next_article is None %}
                    <li class="next disabled"><a href="">后面没有了 <span class="glyphicon glyphicon-chevron-right"></span></a></li>
                    {% else %}
                    <li class="next"><a href="{{ next_article.get_absolute_url }}">{{ next_article.title }} <span class="glyphicon glyphicon-chevron-right"></span></a></li>
                    {% endif %}
                </ul>
                <div class="text-center">
                    <button type="button" class="btn btn-primary" data-toggle="collapse"
                            data-target="#zanzhu">
                        <span class="glyphicon glyphicon-usd"></span> 如果觉得文章对你有帮助，可小额赞助 <span class="glyphicon glyphicon-hand-down"></span>
                    </button>

                    <div id="zanzhu" class="collapse" style="margin-top:25px;">
                        <ul class="list-inline">
                            <li class="list-inline-item">
                                <figure class="figure">
                                    <img src="{% static 'tinysite/assets/pay/weixinpay.jpeg' %}" class="figure-img img-fluid rounded" style="width: 250px">
                                    <figcaption class="figure-caption text-center" style="color: green">微信</figcaption>
                                </figure>
                            </li>
                            <li class="list-inline-item"> </li>
                            <li class="list-inline-item">
                                <figure class="figure">
                                    <img src="{% static 'tinysite/assets/pay/zhifubaopay.jpeg' %}" class="figure-img img-fluid rounded" style="width: 250px">
                                    <figcaption class="figure-caption text-center" style="color: deepskyblue">支付宝</figcaption>
                                </figure>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
document.getElementById({{ article.id }}).setAttribute("class","active");
</script>
{% endblock %}

</body>

</html>

mysite/tinysite/templates/tinysite/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<!-- 加载static目录 -->
{% load static %}

<head>
    <meta charset="utf-8">
    <!-- IE8 的兼容模式 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- 为移动端窗口优化 -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block title %}
    <title>邢为栋的小站</title>
    {% endblock %}

    <meta name="description" content="小站用于发布个人整理的学习教程和经验，以及其他爱好的东西。" />
    <!-- 告诉浏览器页面是否为手持设备优化，会被MobileOptimized覆盖 -->
    <meta name="HandheldFriendly" content="True" />
    <meta name="MobileOptimized" content="320" />

    <!-- 引入 Bootstrap 3.3.7 -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'tinysite/css/style.min.css' %}" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <!-- jQuery (Bootstrap 插件需要引入) -->
    <script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
    <!-- 包含了所有编译插件 -->
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- 为重复的网址或版本指定权威网页 -->
    <link rel="canonical" href="http://www.xingweidong.com/" />
    <!-- 参考https://support.google.com/webmasters/answer/1663744?hl=zh-Hans -->
    <link rel="next" href="http://www.xingweidong.com/page/2/" />

    <!-- Favicons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'tinysite/assets/ico/taiji.png' %}">
    <link rel="shortcut icon" href="{% static 'tinysite/assets/ico/taiji.png' %}">

    {% block extra %}
    {% endblock %}
</head>
{% block body %}
{% endblock %}
</html>

mysite/tinysite/templates/tinysite/column.html
<!DOCTYPE html>
<html lang="zh-CN">
{% extends 'base.html' %}
<!-- 加载static目录 -->
{% load static %}

<head>
    {% block title %}
    <title>邢为栋的小站</title>
    {% endblock %}

    {% block extra %}
    {% endblock %}
</head>

<body>
{% block content %}

<div class="jumbotron">
    <div class="container">
        <div class="row">
            <nav class="col-sm-3">
                <div class="container-fluid">
                <div class="container-fluid collapse navbar-collapse" data-spy="affix">
                    <h3>{{ column.name }}</h3>
                <ul class="nav nav-pills nav-stacked">
                    {% for article in column.article_set.all %}
                    <li>
                        <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
                    </li>
                    {% endfor %}
                </ul>
                </div>
                </div>
            </nav>
            <div class="col-sm-9">
            </div>
        </div>
    </div>
</div>

{% endblock %}
</body>

</html>

mysite/tinysite/templates/tinysite/index.html
<!DOCTYPE html>
<html lang="zh-CN">
{% extends 'tinysite/base.html' %}
<!-- 加载static目录 -->
{% load static %}

<head>
    {% block title %}
    <title>邢为栋的小站</title>
    {% endblock %}

    {% block extra %}
    {% endblock %}
</head>

{% block body %}
<body>

<!-- header -->
<div class="header" style="background-image: url({% static 'tinysite/images/header-background.jpg' %})">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="headertxt">
                    <h1>你好，我是邢为栋</h1>
                    <h2>欢迎来到我的小站</h2>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- 主要内容 -->
<main class="jumbotron" role="main" style="margin-bottom:0">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12">
                <div class="maintxt">
                    <h2><img src="{% static 'tinysite/images/title.png' %}"> 关于小站</h2>
                    <p>小站建设是为了学以致用，同时致力于传播IT相关知识，将所学所得编写成学习笔记和经验，发布到小站，希望可以对光临小站的朋友有所帮助。</p>
                    <p>小站并非专业的教学网站，站内教程和经验仅供参考。小站教程的创作初衷是整理学习资料的同时，希望能够为同学者提供一些帮助。</p>
                    <p>贡献我的一份力，愿与君共勉！</p>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12">
                <div class="maintxt">
                    <h2><img src="{% static 'tinysite/images/title.png' %}"> 站长信条</h2>
                    <p>上善若水。森罗万象。格物致知。</p>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12" style="margin-top:30px">
                <div class="maintxt">
                    <h2><img src="{% static 'tinysite/images/title.png' %}"> 小站内容</h2>
                    {% for category in category_list %}
                    <div class="col-xs-12 col-sm-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    {{ category.category_name }}
                                </h3>
                            </div>
                            <div class="panel-body">
                                <table class="table">
                                    {% for course in category.course_set.all %}
                                    <tr><td>
                                        <h4><a href="{% url 'tinysite:course' course.id %}">{{ course.course_name }}</a></h4>
                                        <p>{{ course.course_description }}</p>
                                    </td></tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</main>


<!-- 页尾-->
<div class="jumbotron text-center" style="margin-bottom:0; background:#202020; color:#959595">
  <ul class="nav nav-pills nav-stacked">
                <li><a href="https://github.com/Xingwd">欢迎关注我的GitHub</a></li>
                <!-- <li><a href="#">链接 2</a></li>
                <li><a href="#">链接 3</a></li> -->
  </ul>
</div>

</body>
{% endblock %}

</html>